### ISSUE TITLE
Syntax examples are inconsistent

### ISSUE THREAD

**Issue by Xiretza** [asvln/analog#2]
The [Variables](https://github.com/asvln/analog/blob/b042aa1a8039ae071d35796f428aa085dc4dd9f4/docs/docs.md#variables) section shows variable declararations looking like this:

> `= pi = 3.1415927`

The [immediately preceding section](https://github.com/asvln/analog/blob/b042aa1a8039ae071d35796f428aa085dc4dd9f4/docs/docs.md#indentation) as well as all the other examples show them looking like this:

> `= pi 3.14`

With no formal syntax it's hard to know what's supposed to be the correct way.

**Comment by asvln** [comment]
Thank you, those inconsistencies have been fixed along with some others. I did all my experimentation in these 3 files so there may be more.

I will keep this open until they are ironed out.
